apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-itunes-app
  namespace: cert-manager
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-itunes-app
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: jesus20.11@hotmail.es
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod-itunes-app
    # Enable the HTTP-01 challenge provider
    solvers:
     - dns01:
        cloudflare:
          email: jesus20.11@hotmail.es
          apiTokenSecretRef:
            name: cloudflare-api-key-secret-itunes-app
            key: cloudflare-token